### ISSUE TITLE
parser should get a new database on every call

### ISSUE THREAD

**Issue by souenzzo** [wilkerlucio/pathom-datomic#6]
ATM, once you create a parser, it will use the same db for all parsers call's

0. parser should get a new db on every call.
0. parse should be able to get a explicit db
0. we need to consider scenarios with "many" datomic connections

**Comment by philiplopez** [comment]
Thanks @souenzzo for raising the issue and making a PR. Your fix has solved my problem too... 

To summarise the problem:

1. Perform a transaction on the connection.
2. Query on a unique entity key (i.e. unique identity in Datomic), which the plugin handles automatically.
3. The pathom-datomic plugin does not return the results (NOT-FOUND) for the transacted data.

However, the queries made to a custom query resolver (via (pcd/query-entities ...)) work fine.

As mentioned, the fix @souenzzo provided solves the problem for this scenario.
